version: "3.9"
services:


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - kafka-network
    # volumes:
    #   - type: volume
    #     source: zk-data
    #     target: /var/lib/kafka/data
    #   - type: volume
    #     source: zk-logs
    #     target: /var/lib/kafka/log
  
  postgres:
    image: debezium/postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
       - kafka-network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    # volumes:
    #   - ./pg-data:/var/lib/postgresql/data
  
  connector:
    image: debezium/connect:latest
    container_name: postgres-connect
    ports:
      - 8083:8083
    links:
      - kafka
    depends_on:
      - kafka
      - postgres
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      BOOTSTRAP_SERVERS: kafka:9092, kafka:9094
    networks:
      - kafka-network
    extra_hosts:
     - "host.docker.internal:172.17.0.1"

networks: 
  kafka-network:
    driver: bridge